### ISSUE TITLE
banned on open proxy

### ISSUE THREAD

**Issue by Awan** [hashbang/hashbang.sh#151]
http://dronebl.org/lookup?ip=2a01:4f8:141:1272::2

freenode has banned my shell.

**Comment by Shinoa-Fores** [comment]
I've noticed in past week can't even connect service bots from hashbang to *any* irc server I've tried.

**Comment by KellerFuchs** [comment]
Presumably caused by a user running an open proxy under their account.  The issue seems gone now, so I can't investigate further  :/

A long-term fix would be to give each user a separate IPv6 address and not let them listen on the server's public-facing IPv4 address.  IIRC I suggested that before my break from the project, but it's a bit more than out of scope for this issue  ^^'
