### ISSUE TITLE
... <(...) isn't POSIX

### ISSUE THREAD

**Issue by Veraellyunjie** [hashbang/hashbang.sh#185]
This isn't POSIX and doesn't work on OpenBSD sh/ksh ([OpenBSD sh is actually ksh](https://man.openbsd.org/sh)):
```
sh <(curl hashbang.sh | gpg)
gpg --verify <(curl https://hashbang.sh)
```
I wouldn't raise the issue, but there are words:
```
# This script first and foremost attempts to be POSIX compliant.
```
The funny thing is it may pertain to the script starting from `#!/bin/sh`, whereas the above `... <(...)` is not part of the script but comes before, so one might argue there is no contradiction :)

I didn't check the rest - I tried hitting user provisioning API directly with an SSH Public Key and desired username, which [1st succeeded then errored then succeeded](https://github.com/hashbang/hashbang.sh/issues/184)

**Comment by RyanSquared** [comment]
This is an annoying situation because on one hand we want a one-liner, but on the other hand there is no way (that I know of) to ensure the script has completely downloaded without using the penguin syntax. This is considered necessary to avoid a situation where the script starts but isn't fully downloaded before running commands.
