### ISSUE TITLE
Inconsistent idea of what usernames are valid

### ISSUE THREAD

**Issue by mwgamera** [hashbang/hashbang.sh#28]
I'm not sure if that is an issue with this script or rather with [hashbang/provisor](/hashbang/provisor) but here this script [assumes](https://github.com/hashbang/hashbang.sh/blob/master/src/hashbang.sh#L138) and instructs the user that username must be between 1 and 31 characters, but then creation of account using 3-letter username fails because [on the server side](https://github.com/hashbang/provisor/blob/6f9ea3ac94e6ba4320fb264e4931c1b358fd09d9/provisor/utils.py#L72) the check is totally different (requires minimum length of 4).

**Comment by lrvick** [comment]
Good catch. Feel free to submit a PR to fix it on the client side. Else one of us will get to it :)

**Comment by mwgamera** [comment]
So server side is the intended one? Damn, and I hoped to get 3-letter name; I guess I should've opened this under provisor but it's too late now ;P

**Comment by lrvick** [comment]
Actually, on consideration the reason for that is due to the fact we used to offer username.hashbang.sh and we didn't want people clobbering up subdomains we would need in the future (all 3 letter server names).

Now it is: 'username.hostname.hashbang.sh' with the new multi-server scheme and we reserve the whole subdomain space and give sub-subdomains to users. Given that, 1-3 letter names are no longer of issue.

I will now close this, and instead ask you submit a PR for provisor, as you suggest. :)

**Comment by mwgamera** [comment]
Okay, wilco later, because it may take me some time to grok the server side.

**Comment by lrvick** [comment]
https://github.com/hashbang/provisor/blob/master/provisor/utils.py#L60-L83 should not be too bad to follow. lmk if you have any questions.
