### ISSUE TITLE
passphrase prompt  for key '~/.ssh/id_rsa.pub'

### ISSUE THREAD

**Issue by Flashwalker** [hashbang/hashbang.sh#32]
When i try to:
`$ ssh hashbang`
it prompts:
`Enter passphrase for key '~/.ssh/id_rsa.pub': `
WTF?

**Comment by necrophcodr** [comment]
Enter the passphrase you entered when you created the SSH key.

**Comment by lrvick** [comment]
Yes. Your local ssh client is asking for the passphrase for your encrypted id_rsa file so it can perform a handshake for you. This is normal.

**Comment by Flashwalker** [comment]
phah, that passphrase, which automatically generated by ssh-keygen with moving mouse and typing `...kchgktgxltgxlk658765t8t&^*Ihbug8P)()*I...`?
and why it's asking? key pair not enough?

**Comment by lrvick** [comment]
When you generate a key pair with ssh-keygen, (in this case RSA) it creates 2 files.

'~/.ssh/id_rsa.pub'  - This is your public key, that is provided to our server
'~/.ssh/id_rsa'  - This is your private key, and it is encrypted with with whatever pass-phrase you chose. 

When you ssh to a server using public/private key encryption a password is not involved on your end at all, only on yours.

An oversimplification of the flow is as follows:

1. You ssh with: `flaskwalker@someserver`
2. sshd sees your connection and checks to see if the account 'flashwalker' has any stored public keys
3. sshd finds a public key for 'flashwalker' and needs to verify you have the matching private half.
4. sshd encrypts a unique 'challange' message (lets call it 'pickles') to your public key, in such a way that only your private key can decrypt it'
5. The message is sent to you, and your local ssh client need to decrypt it to prove itself.
6. Your ssh client finds your .ssh/id_rsa file, but is unable to use it because the key itself is encrypted with a password only you know.
7. Your ssh client asks you for the password to your private key so it can decrypt it
8. Your key is now decrypted into memory where ssh can use it
9. Your ssh client now uses your decrypted private key to decrypt the 'challange' message, revealing it to be pickles.
10. You encrypt a message back to the server saying 'I decrypted your message, it was pickles'
11. Server verifies this response and is now satisfied that you passed the test, and allows you to log in

So yes, while there is a password involved, this password is never transmitted over the network. It also means that if someone steals your private key, they can't use it to log into every server you have access to.

If you want to learn more about encryption and why it matters please ask on IRC. We are happy to help :)

**Comment by Flashwalker** [comment]
ok, thanks, you are convince me.
But bit of strange is that i hadn't enter passphrase during key generation, should i redo?

**Comment by Aagat** [comment]
Yes, that might be a good idea if you haven't used that key elsewhere.

**Comment by Flashwalker** [comment]
by the way, there wasn't ask any passphrase at very first connect after account creation

**Comment by Flashwalker** [comment]
Forgot to say, if i have no passphrase and press enter, it says: Permission denied (publickey).
Can i login wthout passphrase?

**Comment by necrophcodr** [comment]
Probably not. Even if you could, it is a very bad idea. You really should use a passphrase.

**Comment by Flashwalker** [comment]
okay.
