### ISSUE TITLE
hashbang.sh is not responding

### ISSUE THREAD

**Issue by mrmakeit** [hashbang/hashbang.sh#34]
accessing https://hashbang.sh results in a timeout error, both with the root site, and during the user creation process.

**Comment by mrmakeit** [comment]
i should point out that this is a duplicate of #25, which was closed without resolution.

**Comment by lrvick** [comment]
The server was temporarily down. Signup services have since been restored.

On Tue, Apr 14, 2015 at 2:50 PM, Blixa Morgan <notifications@github.com>
wrote:

> i should point out that this is a duplicate of #25
> <https://github.com/hashbang/hashbang.sh/issues/25>, which was closed
> without resolution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashbang/hashbang.sh/issues/34#issuecomment-93078353>.
>



-- 
Lance R. Vick
__________________________________________________
Cell      -  407.283.7596
Gtalk     -  lance@lrvick.net
Website   -  http://lrvick.net
PGP Key   -  http://lrvick.net/0x36C8AAA9.asc
keyserver -  subkeys.pgp.net
__________________________________________________
