### ISSUE TITLE
Error Creating account

### ISSUE THREAD

**Issue by Torx10** [hashbang/hashbang.sh#68]
using ./hashbang.sh I receive:

 Creating your account...  Account creation failed: User creation script failed
 
 If you think this is a bug, please report it to 
 -> https://github.com/hashbang/hashbang.sh/issues/
 
 The installer will not continue from here...

and advanced alternative I receive:
{"message": "User creation script failed"}

my  ~/.ssh/id_rsa.pub was created using ./hashbang.sh

I am unsure if this is a bug or if signups are no longer provided.

**Comment by lrvick** [comment]
Known bug from a recent deploy. Should have healthy version up shortly.

**Comment by Torx10** [comment]
Thank you, will wait for healthy version

**Comment by KellerFuchs** [comment]
This should (finally!) be fixed by commit `0db127c20629307a6b5b450defa3f5a5b36482f8` in [`provisor`](https://github.com/hashbang/provisor).

Unfortunately, Github is derping pretty hard and it's not obvious my push go through, and it clearly didn't trigger a Dockerhub rebuild, so I guess it will be a little while more.  :V

**Comment by KellerFuchs** [comment]
@Torx10 Solved now
