### ISSUE TITLE
Homepage overhaul

### ISSUE THREAD

**Issue by lrvick** [hashbang/hashbang.sh#76]
Perhaps to avoid instantly turning off security cautious users and better meet our education mission we could be more up front with our install paths, while still saying very little and making the implications obvious.

#!

Trust everyone ( Naive )
[one liner]

Trust us ( Easy )
[gpg verify hashbang,sh steps]

Trust no one ( Advanced )
[manual curl api setup steps]

**Comment by KellerFuchs** [comment]
We probably shouldn't give out the oneliner (assuming you mean `curl https://hashbang.sh | gpg | sh`), because it is inherently insecure (if the document is large enough, data will be streamed to `sh` before the signature check is done).

I would be in favour of just showing `curl http://hashbang.sh | gpg > hashbang.sh`, more curious/tinfoil/advanced users can inspect the source and figure out the API.
We should actually encourage that by adding comments that decribe the API.

**Comment by KellerFuchs** [comment]
Nevermind, the API is documented in comments ... in the HTML page.

**Comment by daurnimator** [comment]
The home page right now is stupid... if you actually run it:

```
$ curl hashbang.sh | gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   824  100   824    0     0   1089      0 --:--:-- --:--:-- --:--:--  1089
gpg: no valid OpenPGP data found.
gpg: processing message failed: Unknown system error
```

==> because it gets the "fuck you, use https" message.

**Comment by lrvick** [comment]
closing this as the new path is to have a pure static site and 'ssh hashbang.sh' as the only option
